# https://github.com/streamingfast/graph-node-dev/tree/master/config
[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@host.docker.internal:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.mainnet]
shard = "primary"
provider = [
    # { label = "block-ingestor", url = "$ETH_MAINNET_RPC", features = [] },
    # { label = "bootstrap", details = { type = "web3", url = "$RPC_NODE", features = [ "archive" ] }},
    { label = "substreams-mainnet", details = { type = "substreams", url = "$SUBSTREAMS_ENDPOINT", token = "$SUBSTREAMS_API_TOKEN" }},
    { label = "firehose", details = { type = "firehose", url = "$SUBSTREAMS_ENDPOINT", token = "$SUBSTREAMS_API_TOKEN" }},
    # { label = "firehose", details = { type = "firehose", url = "$FIREHOSE_ENDPOINT", token = "$STREAMING_FAST_API_TOKEN", features = [ "compression", "filters" ] }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]
